//! `Resource`: global singleton resource trait plus resource slot storage.
//!
//! Each resource slot is a type-erased `Arc<RwLock<R>>`; `Res<T>`/`ResMut<T>`
//! are owned guards (`read_arc_recursive`) that may be held across await, and
//! never dangle when the resource is removed.
//!
//! ## Resource keys: layout-derived IDs (safe across DLLs)
//!
//! Rust `TypeId` cannot be used across dynamic libraries: host and cdylib
//! plugin each hold a statically linked copy of a type, so
//! `TypeId::of::<T>()` differs on the two sides and resource lookup would
//! silently fail (the plugin gets `None`). Resource keys are therefore
//! derived from **layout code** into [`ResourceId`]:
//!
//! - layout code = `repr` prefix + struct name + alphabetically ordered
//!   `field:type` list (normalized to a spaceless form, e.g.
//!   `Foo{a:i32,b:i32}`);
//! - ID = SHA-256 of the layout code truncated to 128 bits;
//! - layout code is a pure function of the source: host/plugin copies built
//!   from the same source always derive the same ID, while types with
//!   different field layouts always get different IDs;
//! - **equal IDs imply equal layouts**: the ID itself acts as a layout
//!   certificate, which is what makes rebuilding the strongly typed
//!   `Arc<RwLock<R>>` across DLLs in `get_lock` sound (see its SAFETY note).
//!
//! The key is structural (not nominal): matching fields mean the same
//! resource. This also leaves room for cross-language implementations that
//! follow the same layout protocol.

use parking_lot::RwLock;
use std::any::Any;
use std::collections::HashMap;
use std::fmt;
use std::sync::Arc;
pub use sc_ecs_macros::Resource;

/// Unique resource ID: layout code hashed with SHA-256, truncated to 128 bits.
///
/// Collision probability is negligible for realistic type counts (birthday bound ~2^64 types).
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub struct ResourceId(pub [u8; 16]);

impl ResourceId {
    /// Derives the ID from layout code.
    pub fn from_layout(layout: &str) -> Self {
        use sha2::{Digest, Sha256};
        let mut hasher = Sha256::new();
        hasher.update(layout.as_bytes());
        let digest = hasher.finalize();
        let mut id = [0u8; 16];
        id.copy_from_slice(&digest[..16]);
        Self(id)
    }
}

/// Process-level cache from layout code to ResourceId.
///
/// Code generated by the derive macro must go through this cache: a
/// `static OnceLock` inside a generic function is **not** isolated per
/// monomorphized instance (all instances of the same generic share one
/// static), which once made `Events<A>` and `Events<B>` return the same
/// ResourceId, sharing one slot and reinterpreting each other. A static in a
/// non-generic function is process-unique, and the full layout string as cache
/// key isolates types correctly.
pub fn cached_resource_id(layout: &str) -> ResourceId {
    use std::collections::HashMap;
    use std::sync::{OnceLock, RwLock};
    static CACHE: OnceLock<RwLock<HashMap<String, ResourceId>>> = OnceLock::new();
    let cache = CACHE.get_or_init(|| RwLock::new(HashMap::new()));
    if let Some(id) = cache.read().unwrap().get(layout) {
        return *id;
    }
    let id = ResourceId::from_layout(layout);
    cache.write().unwrap().insert(layout.to_string(), id);
    id
}

/// Cache a derived resource ID by the local concrete type while building the
/// cross-DLL ID from the canonical layout only on the first local lookup.
/// `TypeId` is only a process-local memo key; it is never returned or used as
/// the resource ID, so independently compiled host/plugin copies still derive
/// identical IDs from the canonical layout.
pub fn cached_resource_id_for<T: 'static>(build_layout: impl FnOnce() -> String) -> ResourceId {
    use std::any::TypeId;
    use std::collections::HashMap;
    use std::sync::{OnceLock, RwLock};
    static CACHE: OnceLock<RwLock<HashMap<TypeId, ResourceId>>> = OnceLock::new();
    let cache = CACHE.get_or_init(|| RwLock::new(HashMap::new()));
    let type_id = TypeId::of::<T>();
    if let Some(id) = cache.read().unwrap().get(&type_id) {
        return *id;
    }

    let id = ResourceId::from_layout(&build_layout());
    let mut cache = cache.write().unwrap();
    *cache.entry(type_id).or_insert(id)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicUsize, Ordering};

    struct CacheProbe;

    #[test]
    fn cached_resource_id_for_skips_layout_formatting_after_first_lookup() {
        let builds = AtomicUsize::new(0);
        let first = cached_resource_id_for::<CacheProbe>(|| {
            builds.fetch_add(1, Ordering::SeqCst);
            "CacheProbe{field:u32}".to_string()
        });
        let second = cached_resource_id_for::<CacheProbe>(|| {
            builds.fetch_add(1, Ordering::SeqCst);
            "CacheProbe{field:u32}".to_string()
        });
        assert_eq!(first, second);
        assert_eq!(first, ResourceId::from_layout("CacheProbe{field:u32}"));
        assert_eq!(builds.load(Ordering::SeqCst), 1);
    }

    struct HostProbe;
    struct PluginProbe;

    #[test]
    fn local_type_id_key_does_not_change_canonical_layout_id() {
        let host = cached_resource_id_for::<HostProbe>(|| "SharedLayout{x:u32}".into());
        let plugin = cached_resource_id_for::<PluginProbe>(|| "SharedLayout{x:u32}".into());
        assert_eq!(host, plugin);
    }
}

impl fmt::Debug for ResourceId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let hex: String = self.0.iter().map(|b| format!("{b:02x}")).collect();
        write!(f, "ResourceId({hex})")
    }
}

pub trait Resource {
    /// Layout-derived unique ID (computed by the derive macro from the struct
    /// layout code; generic instantiations carry a runtime `type_name` suffix,
    /// see the `sc_ecs_macros::Resource` docs).
    fn resource_id() -> ResourceId
    where
        Self: Sized;

    fn name() -> String
    where
        Self: Sized;
}

/// Each resource slot is an `Arc<RwLock<R>>` (stored type-erased).
/// `Res<T>`/`ResMut<T>` hold **owned** arc guards (`arc_lock` +
/// `send_guard`) that stay valid across threads and await.
pub struct ResourceManager {
    resources: HashMap<ResourceId, Arc<dyn Any + Send + Sync>>,
    /// ID to first-registered type name (collision detection: the layout code
    /// is the source of the ID, normally one-to-one; same ID with different
    /// types would mean reinterpretation and must surface immediately).
    #[cfg(debug_assertions)]
    id_names: HashMap<ResourceId, &'static str>,
}

impl ResourceManager {
    pub fn new() -> Self {
        Self {
            resources: HashMap::new(),
            #[cfg(debug_assertions)]
            id_names: HashMap::new(),
        }
    }

    pub fn add_resource<R: Resource + 'static + Send + Sync>(&mut self, resource: R) {
        let id = R::resource_id();
        #[cfg(debug_assertions)]
        {
            let name = std::any::type_name::<R>();
            match self.id_names.get(&id) {
                Some(existing) if *existing != name => {
                    // Same layout code but different Rust types: the two types
                    // would share one resource slot and reinterpret each
                    // other (breaks the SAFETY precondition of get_lock).
                    // Either a SHA-128 collision or a hand-written resource_id typo.
                    panic!(
                        "ResourceId collision: {existing} and {name} share {id:?} \
                         (layout-code collision, would cause type confusion)"
                    );
                }
                Some(_) => {}
                None => {
                    self.id_names.insert(id, name);
                }
            }
        }
        self.resources.insert(id, Arc::new(RwLock::new(resource)));
    }

    pub fn remove_resource<R: Resource + 'static + Send + Sync>(&mut self) {
        self.resources.remove(&R::resource_id());
    }

    /// Fetches the lock handle of a resource slot (without locking). The caller picks read/write.
    pub(crate) fn get_lock<R: Resource + 'static + Send + Sync>(&self) -> Option<Arc<RwLock<R>>> {
        let erased = self.resources.get(&R::resource_id())?.clone();
        // SAFETY: the slot was created by the inserting side as
        // `Arc<RwLock<R_insert>>` and erased to `Arc<dyn Any + Send + Sync>`.
        // `ResourceId` is derived from layout code: finding the slot in the
        // map implies this side's R and the inserting side's R_insert share
        // the same layout code, hence the same field names/field types/repr,
        // hence the same `RwLock<R>` vs `RwLock<R_insert>` layout.
        // `Arc::into_raw` takes the data pointer (thin pointer, refcount
        // untouched) and rebuilds `Arc<RwLock<R>>` for this side: both ends
        // are compiled copies of the same source, the Arc header layout and
        // the process-wide System allocator match, so rebuild and later
        // release are sound. With differing layout codes the map lookup above
        // already returned None, so this point is unreachable: i.e. "ID
        // mismatch implies no pointer", with no mis-reinterpretation path.
        let raw = Arc::into_raw(erased) as *const RwLock<R>;
        Some(unsafe { Arc::from_raw(raw) })
    }
}
