[workspace]
members = [
    "crates/sc_async",
    "crates/sc_ecs",
    "crates/sc_ecs/sc_ecs_macros",
    "crates/sc_network",
    "crates/sc_packloader",
    "crates/sc_raknet",
    "crates/sc_binary",
    "crates/sc_binary/sc_binary_macros",
    "crates/sc_utils",
    "crates/sc_log",
    "crates/sc_nbt",
    "crates/sc_bootstrap",
    "crates/sc_network/sc_network_macros",
    "crates/sc_packloader/sc_packloader_macros",
    "crates/sc_entity",
    "crates/sc_eventbus",
    "crates/sc_eventbus/sc_eventbus_macros",
    "crates/sc_world",
    "crates/sc_nbt/sc_nbt_macros",
    "crates/sc_command",
    "crates/sc_item",
    "crates/sc_molang",
    "crates/sc_plugin",
    "crates/sc_plugin/sc_plugin_macros",
    "crates/sc_vanilla/crates/vanilla_command",
    "crates/sc_data_extractor",
    "crates/sc_log_macros",
    "crates/sc_game",
    "crates/sc_recipe",
    "crates/sc_console",
    "crates/sc_plugin_api",
    "crates/sc_vanilla/crates/overworld_generator",
    "crates/sc_vanilla/crates/overworld_generator_host",
    "crates/sc_app/src-tauri",
]
