//! Seeded random sources for world generation.
//!
//! - [`RandomSourceProvider`] trait (fork/identical/next-*/set-seed API)
//! - [`Xoroshiro128`] (splitmix-seeded xoroshiro128 variant)
//! - [`MtRandom`] (Mersenne-Twister-backed source)
//! - Private [`commons`] module: the seed-conversion + sampling helpers the
//!   Mersenne-Twister source needs (seed expansion, twist/temper core,
//!   integer-provider defaults, bounded-range helpers).

// ---------------------------------------------------------------------------
// RandomSourceProvider (random-source interface)
// ---------------------------------------------------------------------------

/// Seeded random-source interface.
///
/// Note: the overloaded `nextInt()` / `nextInt(max)` / `nextInt(min, max)`
/// map to [`Self::next_int`] / [`Self::next_int_max`] /
/// [`Self::next_int_range`], since Rust has no overloading.
pub trait RandomSourceProvider {
    /// Create a new RandomSource using the random long generated by [`Self::next_long`].
    fn fork(&mut self) -> Self
    where
        Self: Sized;

    fn identical(&self) -> Self
    where
        Self: Sized;

    /// Generate random integer between `i32::MIN` and `i32::MAX`.
    fn next_int(&mut self) -> i32;

    /// Generate random integer between 0 and max.
    fn next_int_max(&mut self, max: i32) -> i32;

    /// Generate a random int in the range min-max, include min and max.
    /// (min == max panics on division by zero, matching the reference.)
    fn next_int_range(&mut self, min: i32, max: i32) -> i32;

    fn next_bounded_int(&mut self, max: i32) -> i32;

    /// Generate random long between `i64::MIN` and `i64::MAX`.
    fn next_long(&mut self) -> i64;

    /// Generate random boolean.
    fn next_boolean(&mut self) -> bool;

    /// Next float 0-1.
    fn next_float(&mut self) -> f32;

    /// Next double 0-1.
    fn next_double(&mut self) -> f64;

    /// Next double -1~1 for Gaussian distribution.
    fn next_gaussian(&mut self) -> f64;

    /// Sets a new seed.
    fn set_seed(&mut self, seed: i64);

    fn get_seed(&self) -> i64;
}

// ---------------------------------------------------------------------------
// Xoroshiro128
// ---------------------------------------------------------------------------

/// Xoroshiro128 generator (seedfinding-style xoroshiro128 variant, not the
/// standard xoroshiro128++ — this implementation is authoritative).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Xoroshiro128 {
    seed: i64,
    s0: i64,
    s1: i64,
}

impl Xoroshiro128 {
    /// Builds a generator from an explicit seed (only explicit seeds are
    /// offered; time-based seeding has no place in deterministic
    /// generation).
    pub fn new(seed: i64) -> Self {
        let mut r = Self {
            seed: 0,
            s0: 0,
            s1: 0,
        };
        r.set_seed(seed);
        r
    }

    /// 64-bit left rotation.
    #[inline]
    fn rotate_left(x: i64, k: i32) -> i64 {
        x.rotate_left(k as u32)
    }

    /// Expands one seed into two state words (splitmix64).
    fn split_mix64_seed(seed: i64) -> [i64; 2] {
        let mut out = [0i64; 2];
        let mut z = seed as u64;
        for i in 0..2 {
            z = z.wrapping_add(0x9E37_9B97_F4A7_C15);
            let mut r = z;
            r = (r ^ (r >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
            r = (r ^ (r >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
            r ^= r >> 31;
            out[i] = r as i64;
        }
        if out[0] == 0 && out[1] == 0 {
            out[0] = 0x9E37_9B97_F4A7_C15u64 as i64;
            out[1] = !out[0];
        }
        out
    }
}

impl RandomSourceProvider for Xoroshiro128 {
    /// Forks a child generator seeded by one `next_long()` draw.
    fn fork(&mut self) -> Self {
        Xoroshiro128::new(self.next_long())
    }

    /// Rebuilds an identical generator from the same seed (does not copy
    /// the current state).
    fn identical(&self) -> Self {
        Xoroshiro128::new(self.seed)
    }

    /// Draws a non-negative `i32` from the low 31 bits of `next_long()`.
    fn next_int(&mut self) -> i32 {
        self.next_long() as i32 & i32::MAX
    }

    /// Draws an integer in `[0, max)` (0 when max == 0).
    fn next_int_max(&mut self, max: i32) -> i32 {
        if max == 0 {
            return 0;
        }
        self.next_int() % max
    }

    /// Draws an integer in `[min, max)`.
    fn next_int_range(&mut self, min: i32, max: i32) -> i32 {
        min + self.next_int() % (max - min)
    }

    /// Draws an integer in `[0, max]`.
    fn next_bounded_int(&mut self, max: i32) -> i32 {
        self.next_int_max(max.wrapping_add(1))
    }

    /// Advances the xoroshiro state and returns the output word.
    fn next_long(&mut self) -> i64 {
        let i = self.s0;
        let j = self.s1;
        let k = Self::rotate_left(i.wrapping_add(j), 17).wrapping_add(i);
        let j = j ^ i;
        self.s0 = Self::rotate_left(i, 49) ^ j ^ (j << 21);
        self.s1 = Self::rotate_left(j, 28);
        k
    }

    /// Draws a random boolean from the low bit.
    fn next_boolean(&mut self) -> bool {
        (self.next_long() & 1) != 0
    }

    /// Draws a float in [0, 1) from the top 24 bits.
    fn next_float(&mut self) -> f32 {
        ((self.next_long() as u64 >> 40) as f64 * (1.0 / (1u64 << 24) as f64)) as f32
    }

    /// Draws a double in [0, 1) from the top 53 bits.
    fn next_double(&mut self) -> f64 {
        let bits = self.next_long() as u64 >> 11;
        bits as f64 * (1.0 / (1u64 << 53) as f64)
    }

    /// Draws a Gaussian sample (Box-Muller over two doubles).
    fn next_gaussian(&mut self) -> f64 {
        let u1 = self.next_double();
        let u2 = self.next_double();
        (-2.0 * u1.ln()).sqrt() * (2.0 * std::f64::consts::PI * u2).cos()
    }

    /// Re-seeds the generator (splitmix expansion of the new seed).
    fn set_seed(&mut self, seed: i64) {
        self.seed = seed;
        let st = Self::split_mix64_seed(seed);
        self.s0 = st[0];
        self.s1 = st[1];
    }

    /// Returns the construction seed.
    fn get_seed(&self) -> i64 {
        self.seed
    }
}

// ---------------------------------------------------------------------------
// Seeded Mersenne-Twister RNG and its commons-rng internals
// ---------------------------------------------------------------------------

/// Seed-expansion and sampling helpers backing the Mersenne-Twister source
/// (long-to-int-array seed conversion, twist/temper core, integer-provider
/// defaults, bounded-range helpers).
mod commons {
    /// Mix-strength reduction for seed expansion.
    fn stafford13(mut x: u64) -> u64 {
        x = (x ^ (x >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9); // -4658895280553007687L
        x = (x ^ (x >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB); // -7723592293110705685L
        x ^ (x >> 31)
    }

    /// Expands a long seed into an int array.
    ///
    /// The native MT seed is an `int[624]`; a long seed expands through this.
    pub fn long_to_int_array(input: i64, length: usize) -> Vec<u32> {
        const GOLDEN_GAMMA: u64 = 7046029254386353131; // 0x61C8864680B583EB
        let mut v = input as u64;
        if v == GOLDEN_GAMMA {
            v = !v;
        }
        let mut output = vec![0u32; length];
        let mut i = 0usize;
        while i < length {
            v = v.wrapping_sub(GOLDEN_GAMMA); // Add -7046029254386353131L with wraparound
            let x = stafford13(v);
            output[i] = x as u32;
            if i + 1 < length {
                output[i + 1] = (x >> 32) as u32;
            }
            i += 2;
        }
        output
    }

    /// Mersenne-Twister core (not the textbook MT19937 init_by_array —
    /// state filling is its own variant).
    ///
    /// Also folds in the parent integer-provider's boolean-source bit cache
    /// and default methods.
    #[derive(Clone, Debug)]
    pub struct MersenneTwister {
        mt: [u32; 624],
        mti: usize,
        /// Boolean-source bit cache (starts at 1).
        boolean_source: i32,
    }

    impl MersenneTwister {
        /// Builds twister state from a seed array (initialize + seed-mix +
        /// state-mix).
        pub fn new(seed_ints: &[u32]) -> Self {
            let mut mt = [0u32; 624];
            // fillStateMersenneTwister L49-54
            let seed: &[u32] = if seed_ints.is_empty() {
                // Empty input becomes a length-1 all-zero array
                &[0u32]
            } else {
                seed_ints
            };
            Self::initialize_state(&mut mt);
            let next_index = Self::mix_seed_and_state(&mut mt, seed);
            Self::mix_state(&mut mt, next_index);
            mt[0] = i32::MIN as u32;
            Self {
                mt,
                mti: 624,
                boolean_source: 1,
            }
        }

        /// Initializes the state array.
        fn initialize_state(state: &mut [u32; 624]) {
            let mut mt = 19650218u32;
            state[0] = mt;
            for i in 1..state.len() {
                mt = 1812433253u32
                    .wrapping_mul(mt ^ (mt >> 30))
                    .wrapping_add(i as u32);
                state[i] = mt;
            }
        }

        /// Mixes the seed into the state; returns the next index.
        fn mix_seed_and_state(state: &mut [u32; 624], seed: &[u32]) -> usize {
            let state_size = state.len();
            let mut i = 1usize;
            let mut j = 0usize;
            let mut k = state_size.max(seed.len()) as i64;
            while k > 0 {
                // 64-bit intermediates truncated to the low 32 bits; u32
                // wrapping math matches.
                let a = state[i];
                let b = state[i - 1];
                let c = (a ^ (b ^ (b >> 30)).wrapping_mul(1664525))
                    .wrapping_add(seed[j])
                    .wrapping_add(j as u32);
                state[i] = c;
                j += 1;
                i += 1;
                if i >= state_size {
                    state[0] = state[state_size - 1];
                    i = 1;
                }
                if j >= seed.len() {
                    j = 0;
                }
                k -= 1;
            }
            i
        }

        /// Mixes the state array.
        fn mix_state(state: &mut [u32; 624], start_index: usize) {
            let state_size = state.len();
            let mut i = start_index;
            let mut k = state_size as i64 - 1;
            while k > 0 {
                let a = state[i];
                let b = state[i - 1];
                let c = (a ^ (b ^ (b >> 30)).wrapping_mul(1566083941)).wrapping_sub(i as u32);
                state[i] = c;
                i += 1;
                if i >= state_size {
                    state[0] = state[state_size - 1];
                    i = 1;
                }
                k -= 1;
            }
        }

        /// Produces the next output word (twist + temper).
        pub fn next(&mut self) -> i32 {
            const MAG01: [u32; 2] = [0, 2567483615]; // Java: {0, -1727483681}
            if self.mti >= 624 {
                let mut mt_next = self.mt[0];
                for k in 0..227usize {
                    let mt_curr = mt_next;
                    mt_next = self.mt[k + 1];
                    let y = (mt_curr & 0x8000_0000) | (mt_next & 0x7FFF_FFFF);
                    self.mt[k] = self.mt[k + 397] ^ (y >> 1) ^ MAG01[(y & 1) as usize];
                }
                for k in 227..623usize {
                    let mt_curr = mt_next;
                    mt_next = self.mt[k + 1];
                    let y = (mt_curr & 0x8000_0000) | (mt_next & 0x7FFF_FFFF);
                    self.mt[k] = self.mt[k - 227] ^ (y >> 1) ^ MAG01[(y & 1) as usize];
                }
                let y = (mt_next & 0x8000_0000) | (self.mt[0] & 0x7FFF_FFFF);
                self.mt[623] = self.mt[396] ^ (y >> 1) ^ MAG01[(y & 1) as usize];
                self.mti = 0;
            }
            let mut y = self.mt[self.mti];
            self.mti += 1;
            y ^= y >> 11;
            y ^= (y << 7) & 0x9D2C_5680;
            y ^= (y << 15) & 0xEFC6_0000;
            y ^= y >> 18;
            y as i32
        }

        /// Next output word.
        #[inline]
        pub fn next_int(&mut self) -> i32 {
            self.next()
        }

        /// Next boolean; each output word also refills a 31-bit boolean cache.
        pub fn next_boolean(&mut self) -> bool {
            let mut bits = self.boolean_source;
            if bits == 1 {
                bits = self.next();
                // Keep the sign bit, shift the rest as unsigned
                self.boolean_source = i32::MIN | ((bits as u32 >> 1) as i32);
                return (bits & 1) == 1;
            }
            self.boolean_source = ((bits as u32) >> 1) as i32;
            (bits & 1) == 1
        }

        /// Combines two output words into a long.
        pub fn next_long(&mut self) -> i64 {
            let v = self.next();
            let w = self.next();
            // Java: (long)v << 32 | (long)w & 0xFFFFFFFFL
            ((v as i64) << 32) | (w as i64 & 0xFFFF_FFFF)
        }

        /// Combines two output words into a [0, 1) double.
        pub fn next_double(&mut self) -> f64 {
            let v = self.next() as u32;
            let w = self.next() as u32;
            // Java: high = ((long)(v >>> 6)) << 27; low = w >>> 5; (high|low) * 0x1.0p-53
            let high = ((v >> 6) as u64) << 27;
            let low = (w >> 5) as u64;
            ((high | low) as f64) * (1.0 / (1u64 << 53) as f64)
        }

        /// Next float in [0, 1) from the top 24 bits.
        pub fn next_float(&mut self) -> f32 {
            ((self.next() as u32 >> 8) as f32) * (1.0f32 / (1u32 << 24) as f32)
        }

        /// Bounded int via multiply-high with rejection sampling.
        /// Callers must pass `n > 0` (enforced by debug_assert).
        pub fn next_int_n(&mut self, n: i32) -> i32 {
            debug_assert!(n > 0, "Upper bound must be above zero: {n}");
            let n = n as u64;
            let mut m = (self.next() as u32 as u64).wrapping_mul(n);
            let mut l = m & 0xFFFF_FFFF;
            if l < n {
                let t = 0x1_0000_0000u64 % n;
                while l < t {
                    m = (self.next() as u32 as u64).wrapping_mul(n);
                    l = m & 0xFFFF_FFFF;
                }
            }
            (m >> 32) as i32
        }

        /// Ranged int draw; requires `origin < bound` (enforced by
        /// debug_assert).
        pub fn next_int_range(&mut self, origin: i32, bound: i32) -> i32 {
            debug_assert!(origin < bound, "Invalid range: [{origin}, {bound})");
            let n = bound.wrapping_sub(origin);
            if n > 0 {
                return self.next_int_n(n).wrapping_add(origin);
            }
            let mut v = self.next();
            while v < origin || v >= bound {
                v = self.next();
            }
            v
        }

        /// Builds a twister from a long seed (long → int[624] → state).
        pub fn from_long_seed(seed: i64) -> Self {
            Self::new(&long_to_int_array(seed, 624))
        }
    }
}

/// Seeded Mersenne-Twister random source.
///
/// `next_gaussian` uses Box-Muller × 0.33333 clamped to [-1, 1]. That is the
/// only intentional distribution-level deviation in this file; it only
/// affects tall-grass decoration, never terrain determinism.
#[derive(Clone, Debug)]
pub struct MtRandom {
    /// Construction seed.
    seeds: i64,
    provider: commons::MersenneTwister,
}

impl MtRandom {
    /// Builds the generator from a seed.
    pub fn new(seeds: i64) -> Self {
        let mut r = Self {
            seeds: 0,
            provider: commons::MersenneTwister::from_long_seed(0),
        };
        r.set_seed(seeds);
        r
    }

    /// Draws an int in `[min, max]`.
    pub fn next_range(&mut self, min: i32, max: i32) -> i32 {
        self.provider.next_int_range(min, max.wrapping_add(1))
    }
}

impl RandomSourceProvider for MtRandom {
    /// Re-seeds the generator.
    fn set_seed(&mut self, seed: i64) {
        self.seeds = seed;
        self.provider = commons::MersenneTwister::from_long_seed(seed);
    }

    /// Forks a child generator.
    fn fork(&mut self) -> Self {
        MtRandom::new(self.next_long())
    }

    /// Draws an int in `[min, max]`.
    fn next_int_range(&mut self, min: i32, max: i32) -> i32 {
        self.provider.next_int_range(min, max.wrapping_add(1))
    }

    /// Draws an int in `[0, bound]`.
    fn next_bounded_int(&mut self, bound: i32) -> i32 {
        self.next_int_max(bound)
    }

    /// Draws an int in `[0, max]`.
    fn next_int_max(&mut self, max: i32) -> i32 {
        self.provider.next_int_n(max.wrapping_add(1))
    }

    /// Draws a full-range int.
    fn next_int(&mut self) -> i32 {
        self.provider.next_int()
    }

    /// Draws a full-range long.
    fn next_long(&mut self) -> i64 {
        self.provider.next_long()
    }

    /// Draws a double in [0, 1).
    fn next_double(&mut self) -> f64 {
        self.provider.next_double()
    }

    /// Draws a Gaussian sample; see the type docs for the distribution note.
    fn next_gaussian(&mut self) -> f64 {
        let u1 = self.next_double();
        let u2 = self.next_double();
        let sample = (-2.0 * u1.ln()).sqrt() * (2.0 * std::f64::consts::PI * u2).cos() * 0.33333;
        // Java: Math.min(1, Math.max(sample, -1))
        1.0f64.min(sample.max(-1.0))
    }

    /// Draws a float in [0, 1).
    fn next_float(&mut self) -> f32 {
        self.provider.next_float()
    }

    /// Draws a random boolean.
    fn next_boolean(&mut self) -> bool {
        self.provider.next_boolean()
    }

    /// Returns the construction seed.
    fn get_seed(&self) -> i64 {
        self.seeds
    }

    /// Rebuilds an identical generator from the same seed.
    fn identical(&self) -> Self {
        MtRandom::new(self.seeds)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn xoroshiro128_self_consistency() {
        // identical rebuilds from the same seed: matches the post-setSeed sequence
        let mut a = Xoroshiro128::new(12345);
        let mut b = a.identical();
        assert_eq!(a.get_seed(), b.get_seed());
        let sa: Vec<i64> = (0..8).map(|_| a.next_long()).collect();
        let sb: Vec<i64> = (0..8).map(|_| b.next_long()).collect();
        assert_eq!(sa, sb);

        // fork seeds from nextLong()
        let mut c = Xoroshiro128::new(777);
        let mut d = c.clone();
        let fork_seed = d.next_long();
        let mut f = Xoroshiro128::new(fork_seed);
        let mut e = c.fork();
        assert_eq!(f.next_long(), e.next_long());
    }

    #[test]
    fn xoroshiro128_all_zero_splitmix_guard() {
        // State is never all-zero after construction, so nextLong advances
        // normally (defensive check of the all-zero guard)
        for seed in [
            0i64,
            1,
            -1,
            i64::MAX,
            i64::MIN,
            0x9E37_9B97_F4A7_C15u64 as i64,
        ] {
            let mut r = Xoroshiro128::new(seed);
            let _ = r.next_long();
            let _ = r.next_long();
        }
    }

    #[test]
    fn nukkit_random_mt_distinct_streams() {
        let mut a = MtRandom::new(1);
        let mut b = MtRandom::new(2);
        let va: Vec<i32> = (0..8).map(|_| a.next_int()).collect();
        let vb: Vec<i32> = (0..8).map(|_| b.next_int()).collect();
        assert_ne!(va, vb);
        // setSeed resets the stream
        let mut c = MtRandom::new(1);
        c.set_seed(2);
        assert_eq!(vb, (0..8).map(|_| c.next_int()).collect::<Vec<_>>());
        // identical shares the seed
        let mut d = MtRandom::new(42);
        let mut e = d.identical();
        assert_eq!(
            (0..4).map(|_| d.next_int()).collect::<Vec<_>>(),
            (0..4).map(|_| e.next_int()).collect::<Vec<_>>()
        );
    }

    #[test]
    fn nukkit_random_bounded_int_range() {
        let mut r = MtRandom::new(20260823);
        for _ in 0..200 {
            let v = r.next_bounded_int(6);
            assert!((0..=6).contains(&v), "nextBoundedInt(6) out of range: {v}");
        }
        for _ in 0..200 {
            let v = r.next_int_range(-3, 5);
            assert!((-3..=5).contains(&v), "nextInt(-3,5) out of range: {v}");
        }
    }
}
