[package]
name = "sc_plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
sc_ecs = { path = "../sc_ecs" }
sc_plugin_api = { path = "../sc_plugin_api" }
sc_log = { path = "../sc_log" }
sc_binary = { path = "../sc_binary" }
sc_utils = { path = "../sc_utils" }
sc_plugin_macros = { path = "sc_plugin_macros" }
libloading = "=0.9.0"
zip = "=8.6.0"
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = "=1.0.151"
log = "0.4.22"
chrono = "=0.4.45"